# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: twistcli-scan@1
  inputs:
    scanType: 'images'
    twistlockService: 'Prisma cloud compute test'
    vulnerabilityThreshold: 'low'
    onlyFixed: false
    gracePeriod: '0'
    complianceThreshold: 'low'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
