version: 2.1
description: 'Test orb for prisma scan orb'

orbs:
  scan: panw-ns/prisma-cloud@dev:first

jobs:
  scan-image: scan/prisma_cloud

workflows:  
  scan:
    jobs:
      - scan-image:
          access_key: $PC_ACCESS_KEY
          secret_key: PC_SECRET_KEY 
          prisma_cloud_api_url: $PC_CLOUD_API_URL #Get it here <link>
          #templates_directory_path: ./demo/eks.tf.json
          failure_threshold_high_severity: 1
          failure_threshold_medium_severity: 2
          failure_threshold_low_severity: 3
          failure_threshold_operator: and

