version: 2.1
description: 'This is an inline job'

orbs:
  scan_image:
    jobs:
      scan_job:
        executor: default
        parameters:
          pc_username:
            description: Username for authnetication
            type: string
            #default: techops+provision@redlock.io
          pc_password:
            description: User password for authentication
            type: string
            #default: iYS2ZjfKHyQcQpIg55RP
          pc_host:
            description: host url for getting the token
            type: string
            #default: https://api-skat27e9.castles.prismacloud.io/login
        steps:
          - checkout
          - run: pwd
          - run: ls
          - run: zip -r repo.zip .
          - run: ls
          - echo_command 
        #  - auth:
        #      pc_username: <<parameters.pc_username>>
        #      pc_password: <<parameters.pc_password>>
        #      pc_host: <<parameters.pc_host>>        
          - scan
    commands:
      echo_command:
        steps:
           - run: echo "my custom checkout"
      auth:
        description: API call for authentication. User input will be host, username & password. Response will be the auth token to be passed on in scan command.
        parameters:
          pc_username:
            description: Username for authnetication
            type: string
            #default: techops+provision@redlock.io
          pc_password:
            description: User password for authentication
            type: string
            #default: iYS2ZjfKHyQcQpIg55RP
          pc_host:
            description: host url for getting the token
            type: string          
            #default: https://api-skat27e9.castles.prismacloud.io/login
        steps:
          - run: 
              command: |
                token=$(curl -X POST <<parameters.pc_host>> -H 'Content-Type:application/json' -d '{"username":"<<parameters.pc_username>>", "password":"<<parameters.pc_password>>"}'|jq .token| tr -d '"') 
                echo "token: " $token
                export AUTH_TOKEN=$token
      scan:
        description: Scan the repo for vulnerabilities in the templates against default and custom rules
        steps:
          #- run: curl -X POST https://scanapi.redlock.io/v1/iac --output ~/demo1.txt curl -X POST https://api-skat27e9.castles.prismacloud.io/prisma_scan -H 'x-redlock-auth:$AUTH_TOKEN' -d
          - run:
              command: |
                response=$(curl -X POST https://scanapi.redlock.io/v1/iac --data-binary @repo.zip)
                result="$(echo "$response" | jq -r '.result.is_successful')"
                matched="$(echo "$response" | jq -r '.result.rules_matched')"
                stats="$(echo "$response" | jq -r '.result.severity_stats')"
                echo "result: " $result
                echo "matched: " $matched
                echo "stats: " $stats
                mkdir results
                echo $matched | jq -r '.[] | "\(.name)\t\(.severity)\t\(.rule)\t\(.files)'" 
                echo $matched | jq -r '.[] | "\(.name)\t\(.severity)\t\(.rule)\t\(.files)'"> results/matched
          - store_artifacts:
              path: results/matched
    executors:
      default:
        machine: true

workflows:  
  build-test-deploy:
    jobs:
      - scan_image/scan_job:
          pc_username: techops+provision@redlock.io
          pc_password: LjXgyP11CsjeF86ZAVps 
          pc_host: https://api-kratcce2.castles.prismacloud.io/login

