version: 2.1
description: 'This is an inline job'

orbs:
  scan_image:
    orbs:
      twistcli: twistlock/twistcli-scan@1.0.5
    jobs:
      iac_scan_job:
        executor: default
        parameters:
          pc_username:
            description: Username for authnetication
            type: string
            #default: techops+provision@redlock.io
          pc_password:
            description: User password for authentication
            type: string
            #default: iYS2ZjfKHyQcQpIg55RP
          pc_host:
            description: host url for getting the token
            type: string
            #default: https://api-skat27e9.castles.prismacloud.io/login
          variable_file_names:
            description: Take the custom variable file names from the user. This is a comma separated list.
            type: string
            default: ""
          directory_path:
            description: If the user wants to give any directory path other than current working directory.
            type: string
            default: .
          high_cve:
            description: High count of vulnerabilities above which the build should fail.
            type: integer
            default: 0
          medium_cve:
            description: Medium count of vulnerabilities above which the build should fail.
            type: integer
            default: 0
          low_cve:
            description: Low count of voluneabilities above which the build should fail.
            type: integer
            default: 0
        steps:
          - checkout
          #- run: zip -r repo.zip . -x ".*"
          - auth:
              pc_username: <<parameters.pc_username>>
              pc_password: <<parameters.pc_password>>
              pc_host: <<parameters.pc_host>>        
          - scan:
              variable_file_names: <<parameters.variable_file_names>>
              directory_path: <<parameters.directory_path>>
              high_cve: <<parameters.high_cve>>
              medium_cve: <<parameters.medium_cve>>
              low_cve: <<parameters.low_cve>>
      twistlock_job:
        executor: twistcli/default
        parameters:
          tl_user:
            description: The Twistlock Console user with the CI User role
            type: string
            default: $TL_USER
          tl_pass:
            description: The Twistlock Console user's password
            type: env_var_name
            default: TL_PASS
          tl_console_url:
            description: The base URL for the console -- http://console.<my_company>.com:8083 -- without a trailing /
            type: string
            default: $TL_CONSOLE_URL
          pc_username:
            description: Username for authnetication
            type: string
          pc_password:
            description: User password for authentication
            type: string
          pc_host:
            description: host url for getting the token
            type: string
          vuln-thresh:
            description: Sets the minimum vulnerability severity that returns a fail exit code. Supported values are low, medium, high, and critical 
            type: string
            default: ''
          comp-thresh:
            description: Sets the minimum compliance issue severity that returns a fail exit code. Supported values are low, medium, high, and critical 
            type: string
            default: ''
          only-fixed:
            description: Whether to only report vulnerabilities with fixes available
            type: boolean
            default: false 
          workspace-name:
            description: Name of workspace to docker save the image-tar into so it can be scanned by orb
            type: string
            default: workspace 
          image-tar:
            description: The name of the image tar file stored in the workspace -- defaults to image.tar
            type: string
            default: image.tar
          image:
            description: The name of the image to scan -- myimage or myorg/myimage or myorg/myimage:latest
            type: string
        steps: 
          - twistcli/scan-image:
                tl_user: <<parameters.tl_user>>
                tl_pass: <<parameters.tl_pass>>
                tl_console_url: <<paramteres.tl_console_url>>
                image: <<parameters.image>>
                image-tar: <<parameters.image-tar>>
                vuln-thresh: <<parameters.vuln-thresh>>
                comp-thresh: <<parameters.comp-thresh>>
                only-fixed: <<parameters.only-fixed>>
            
    commands:
      auth:
        description: API call for authentication. User input will be host, username & password. Response will be the auth token to be passed on in scan command.
        parameters:
          pc_username:
            description: Username for authnetication
            type: string
          pc_password:
            description: User password for authentication
            type: string
          pc_host:
            description: host url for getting the token
            type: string          
        steps:
          - run: 
              command: |
                token=$(curl -X POST <<parameters.pc_host>>/login -H 'Content-Type:application/json' -d '{"username":"<<parameters.pc_username>>", "password":"<<parameters.pc_password>>"}'|jq .token| tr -d '"') 
                echo "token: " $token
                echo "export AUTH_TOKEN=${token}" >> $BASH_ENV
                echo "export PC_HOST=<<parameters.pc_host>>" >> $BASH_ENV
      scan:
        description: Scan the repo for vulnerabilities in the templates against default and custom rules
        parameters:
          variable_file_names:
            description: Take the custom variable file names from the user. This is a comma separated list.
            type: string
            default: ""
          directory_path:
            description: If the user wants to give any directory path other than current working directory.
            type: string
            default: .
          high_cve:
            description: High count of vulnerabilities above which the build should fail.
            type: integer 
            default: 0
          medium_cve:
            description: Medium count of vulnerabilities above which the build should fail.
            type: integer
            default: 0
          low_cve:
            description: Low count of voluneabilities above which the build should fail.
            type: integer
            default: 0   
        steps:
          - run:
              command: |
                source $BASH_ENV
                vi "$BASH_ENV"
                #echo "AUTH_TOKEN: " ${AUTH_TOKEN}
                echo "PC_HOST: " ${PC_HOST}
                SCAN_PATH=<<parameters.directory_path>>
                if [[ -f <<parameters.directory_path>> ]]
                then
                  mkdir scan;
                  cp <<parameters.directory_path>> scan/
                  SCAN_PATH=scan/
                fi
                zip -r repo.zip $SCAN_PATH -x ".*"
                if [[ variable_file_names != "" ]]
                then
                  response=$(curl -X POST "$PC_HOST"/iac_scan -H "x-redlock-auth:${AUTH_TOKEN}" -H 'rl-variable-file-names: [<<parameters.variable_file_names>>]' -F templateFile=@repo.zip)
                else
                  response=$(curl -X POST $"PC_HOST"/iac_scan -H "x-redlock-auth:${AUTH_TOKEN}" -F templateFile=@repo.zip)
                fi

                #echo "response: " $response
                result="$(echo "$response" | jq -r '.result.is_successful')"
                #echo "result: " $result

                if [[ $result ]]
                then
                  matched="$(echo "$response" | jq -r '.result.rules_matched')"
                  #echo "matched: " $matched
                  if [[ $matched != null ]]
                  then
                    stats="$(echo "$response" | jq -r '.result.severity_stats')"
                    #echo "stats: " $stats
                    mkdir results
                    echo $matched | jq -r '(["SEVERITY","NAME","FILES"] | (., map(length*"-"))), (.[] | [.severity, .name, .files[0]]) |@tsv'> results/scan_results.csv
                    head -n 1 results/scan_results.csv > results/scan.csv && tail -n +2 results/scan_results.csv | sort -t "|" -k 1 >> results/scan.csv
                    #cat results/scan.csv | sed 's/,/ ,/g' | column -t -s, | less -S
                    #cat results/scan.csv | column -t -s, | less -S
                    echo "<html>" ; echo "<body>" ; echo "<table>" ; while read INPUT ; do echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ; done < results/scan_results.csv ; echo "</table>"; echo "</body>" ; echo "</html>"
                    (echo "<html>" ;
                       echo "<body>" ;
                         echo "<table>" ;
                           while read INPUT ;
                             do
                               echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ;
                             done < results/scan_results.csv ;
                         echo "</table>";
                       echo "</body>" ;
                     echo "</html>") >results/results.html
                     high="$(echo "$stats" | jq -r '.high')"
                     med="$(echo "$stats" | jq -r '.medium')"
                     low="$(echo "$stats" | jq -r '.low')"
       
                     if [[ ( "$high" -ge <<parameters.high_cve>> )  || ( "$medium" -ge <<parameters.medium_cve>> ) || ( "$low" -ge <<parameters.low_cve>> ) ]]
                     then
                       echo "The build failed because the vulnerability count crossed the threshold values."
                       echo "Statastics: " $stats
                       exit 1;
                     fi
                     echo "Build successful. All the vulnerability count parameters are under threshold value."
                     echo "Statastics: " $stats
                  fi
                  echo "Build successful. No vulneravilities found."
                  echo "Build successful. No vulneravilities found." > results/scan.csv
                else
                  echo "$(echo "$response" | jq -r '.result.is_successful')"
                  echo "$(echo "$response" | jq -r '.result.is_successful')" > results/scan.csv
                fi  
          - store_artifacts:
              path: results/scan.csv
    executors:
      default:
        machine: true

workflows:  
  build-test-deploy:
    jobs:
      - scan_image/iac_scan_job:
          pc_username: techops+provision@redlock.io
          pc_password: LjXgyP11CsjeF86ZAVps 
          pc_host: https://api-kratcce2.castles.prismacloud.io
          directory_path: ./demo/eks.tf.json
