version: 2.1
description: 'This is an inline job'

#orbs:
 # scan_image:
orbs:
  twistcli: twistlock/twistcli-scan@1.0.5
jobs:
  prisma-cloud-compute-twistcli-scan-try: twistcli/scan-image

workflows:  
  scan:
    jobs:
      - prisma-cloud-compute-twistcli-scan-try:
          tl_user: test
          tl_console_url: "http://18.217.116.33:8081"
          tl_pass: TL_PASS
          image: "image.tar"
