version: 2.1
orbs:
  twistcli: twistlock/twistcli-scan@1.0.4
jobs:
  docker-build-and-save:
    executor: twistcli/default
    steps:
      - checkout
      - run: 'docker build -t myrepo/myimage:tag .'
      - run: mkdir -p workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
  prisma-cloud-compute-scan: twistcli/scan-image

workflows:
  scan-image:
    jobs:
      - docker-build-and-save
      - prisma-cloud-compute-scan:
          requires:
            - docker-build-and-save
          context: tl_scan_context
          image: 'myrepo/myimage:tag'
          image-tar: image.tar
          vuln-thresh: critical
          comp-thresh: ''
          only-fixed: true
