version: 2.1
orbs:
  twistcli: twistlock/twistcli-scan@1.0.4
jobs:
  docker-build-and-save:
    executor: twistcli/default
    steps:
      - checkout
      - run: 'docker build -t myrepo/myimage:tag .'
      - run: mkdir -p workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
  prisma-cloud-compute-scan: twistcli/scan-image

workflows:
  scan-image:
    jobs:
      - prisma-cloud-compute-scan:
          tl_user: test
          tl_console_url: "http://18.217.116.33:8081"
          tl_pass: TL_PASS
          image: "image.tar"
