version: 2.1
description: 'This is an inline job'

orbs:
  scan_image:
    jobs:
      scan_job:
        executor: default
        steps:
          - checkout
          - echo_command 
          - scan
    commands:
      echo_command:
        steps:
           - run: echo "my custom checkout"
      scan:
        description: Scan the repo for vulnerabilities in the templates against default and custom rules
        steps:
          - run: curl --proxy http://127.0.0.1:8080 -X POST https://scanapi.redlock.io/v1/iac --output ~/demo1.txt
    executors:
      default:
        machine: true

workflows:  
  build-test-deploy:
    jobs:
      - scan_image/scan_job

